### ISSUE TITLE
Set the default of the wiki search to 'everything'

### ISSUE THREAD

**Issue by abimysoc** [mysociety/internal#14]
https://www.mediawiki.org/wiki/Manual:$wgNamespacesToBeSearchedDefault

Individuals can do this in their preferences https://wiki.mysociety.org/wiki/Special:Preferences#mw-prefsection-searchoptions but it would be better to set that globally for everyone.

**Comment by dracos** [comment]
Think it's better to use https://www.mediawiki.org/wiki/Manual:$wgDefaultUserOptions for simplicity, added.
