### ISSUE TITLE
'donate' tweetable/FBable graphics

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/internal#15]
Would be nice to tweet out a few messages asking for Xmas donations when our site banners are up.

Messages:

Help us make websites that matter
Help us make the websites that help you
Help us make democracy accessible

**Comment by zarino** [comment]
Examples from @MyfanwyNixon of how our sites help people:

* https://www.mysociety.org/2016/08/19/how-350-foi-requests-will-increase-the-chance-of-success-for-start-ups/
* https://www.mysociety.org/2016/04/20/west-ham-stadium-ruling-a-win-for-transparency/
* https://www.mysociety.org/2016/05/12/does-your-council-break-the-law/
* https://www.mysociety.org/2016/11/22/workfare-what-happens-when-the-government-doesnt-want-to-release-information/
* https://www.mysociety.org/2016/03/09/patent-oppositions-re-igniting-a-campaign-for-fairer-access-to-drugs/

As I said to Myf earlier in IRC:

> I'm tempted to go all out on the heart string pulling […] like, african children, lonely old ladies, cold protestors in the streets, sad child looking directly to camera […] but we can really only get away with images like that if we have an excuse – like a site that might conceivably help those sorts of people

**Comment by zarino** [comment]
Storing these here while we think about what the ads should say and look like.

I have 2 shutterstock download credits left to use in the 127 days, so might as well use them. Further credits are £32 for 5, so £6 per picture.

Examples of the sort of image I was imagining:

[![stock-photo-a-sad-boy-and-a-girl-in-the-townships-103261184](https://cloud.githubusercontent.com/assets/739624/21045348/e77ba374-bdf7-11e6-877a-18e881c2ad67.jpg)](https://www.shutterstock.com/pic-103261184/stock-photo-a-sad-boy-and-a-girl-in-the-townships.html)

[![stock-photo-istanbul-turkey-april-unidentified-muslim-demonstrators-in-turkey-protested-the-education-240484534](https://cloud.githubusercontent.com/assets/739624/21045384/0399d3a0-bdf8-11e6-9594-43584e504044.jpg)](https://www.shutterstock.com/pic-240484534.html)

[![stock-photo-kiev-ukraine-dec-unidentified-homeless-boy-play-on-the-cold-street-during-anti-government-179930666](https://cloud.githubusercontent.com/assets/739624/21045400/15601568-bdf8-11e6-8947-53cafcefc8cc.jpg)](https://www.shutterstock.com/pic-179930666.html)

[![stock-photo-young-mother-with-her-daughter-lying-in-leaves-on-an-autumns-day-329508683](https://cloud.githubusercontent.com/assets/739624/21045601/0153cdde-bdf9-11e6-8d2d-fa16a2a3754e.jpg)](https://www.shutterstock.com/pic-329508683/stock-photo-young-mother-with-her-daughter-lying-in-leaves-on-an-autumns-day.html)

[![stock-photo-little-schoolgirl-using-digital-tablet-at-desk-with-classmates-studying-in-background-145435537](https://cloud.githubusercontent.com/assets/739624/21045422/33c59f8c-bdf8-11e6-8a01-c37617858fef.jpg)](https://www.shutterstock.com/pic-145435537/stock-photo-little-schoolgirl-using-digital-tablet-at-desk-with-classmates-studying-in-background.html)

[![stock-photo-portrait-of-grandmother-with-her-grandson-412975354](https://cloud.githubusercontent.com/assets/739624/21045429/415a1a4c-bdf8-11e6-8c17-16b5387bad28.jpg)](https://www.shutterstock.com/pic-412975354.html)

[![stock-photo-syrian-refugees-sitiation-in-gaziantep-turkey-september-397733653](https://cloud.githubusercontent.com/assets/739624/21045444/4d4d0f62-bdf8-11e6-9356-4de2c535516f.jpg)](https://www.shutterstock.com/pic-397733653/stock-photo-syrian-refugees-sitiation-in-gaziantep-turkey-12-september-2015.html)

[![stock-photo-syrian-refugees-who-came-from-aleppo-waiting-at-the-refugee-camp-in-essalame-border-gate-on-turkey-392531953](https://cloud.githubusercontent.com/assets/739624/21045456/58d56686-bdf8-11e6-9481-32b71a9c7884.jpg)](https://www.shutterstock.com/pic-392531953.html)

**Comment by MyfanwyNixon** [comment]
The messages are going to be key: if we're going to use images like these, then (obviously) the wording has to make sense of why. Here are a few trains of thought:

1) Since the communications thrust is all about impact, we could go down the route of highlighting results.  

This year we : 
- Helped you follow the Supreme Court's Article 50 hearing
- Kept you informed through some of the UK's most dramatic politics for years
- Collected your cycling collision reports as open data to help everyone make our streets safer
- Collated and shared open data on every politician in the world
- Told you how your MP campaigned on Brexit
- Campaigned to keep our rights under FOI
- Helped people in xx countries run sites to fight corruption, open parliaments and give access to information
- Helped you see how your MP voted on lots more topics
- Showed you how your MP performs on responding to constituents
- Helped all kinds of campaigns in getting their supporters to write to their MPs

... and probably lots more if we put our minds to it (I haven't included commercial projects because we'd probably be criticised for raising money on the back of them, and rightly so).

So a request for a donation could run through all of those - even as a flick through a series of images rather than just one. We could still use emotive images if they tied in to the meanings - for example, 'how your MP voted' could have an image of Syria.

2) Or we could use the real people we've helped. We mostly have WDTK stories, though we have a couple of international ones too. 

- Lucie used WhatDoTheyKnow to find out which of our children's schools contain asbestos. Help us help more people uncover the facts that matter.

- Frank used WhatDoTheyKnow to obtain a full list of the companies using unpaid labour on the Workfare scheme.

- Gavin used WhatDoTheyKnow to help start-up businesses succeed

- [An anonymous user] used WhatDoTheyKnow to reveal which councils are paying workers less than the minimum wage

- Richard used WhatDoTheyKnow to find out the truth behind the West Ham stadium

- Nany used FixMyStreet to prove that funds had been misappropriated by corrupt officials in Malaysia


3) If we don't go down the impact route there are various ways you could utilise your tearjerker imagery: 

We give you the power to find out what the government is doing in your name (picture of Syria)

We inform you about what your MP is voting for (picture of food banks/fracking/council houses)

We give you the power to tell your MP how you feel (your grandma pic above might work here)

We help you get things fixed (pic of windblown rubbish-strewn street etc)

Copying in @markcridge as I think the messaging will be really important to get right.

**Comment by MyfanwyNixon** [comment]
That grandma picture or the innocent kids at school - could both go well with "is there asbestos in your kids' school? Fortunately there's a simple way to find out".

**Comment by MyfanwyNixon** [comment]
Soooo... with Zarino away I've had a bit of a go at putting these together. What do you think @markc? Would you be happy with us tweeting these out over well-spaced intervals across the hols?

The idea is that a) people see just how much we do and b) hopefully at least one message speaks to their personal interests.

![mysoc 2016 2](https://cloud.githubusercontent.com/assets/944656/21313508/2c3891a8-c5ea-11e6-9bc7-4f2d9f1def22.png)

![mysoc 2016 3](https://cloud.githubusercontent.com/assets/944656/21313583/b08a4104-c5ea-11e6-8912-75aabd14b794.png)

![mysoc 2016 11](https://cloud.githubusercontent.com/assets/944656/21313586/b64a8748-c5ea-11e6-99a7-1853b768446d.png)

![mysoc 2016 10](https://cloud.githubusercontent.com/assets/944656/21313589/b6736a00-c5ea-11e6-8155-bc2631b9a83c.png)

![mysoc 2016 9](https://cloud.githubusercontent.com/assets/944656/21313590/b6744222-c5ea-11e6-99fe-ba8830018c8f.png)

![mysoc 2016 8](https://cloud.githubusercontent.com/assets/944656/21313591/b6749826-c5ea-11e6-8393-17e79aaa1759.png)

![mysoc 2016 7](https://cloud.githubusercontent.com/assets/944656/21313588/b67343d6-c5ea-11e6-9795-3fa5ece69bc2.png)

![mysoc 2016 6](https://cloud.githubusercontent.com/assets/944656/21313587/b662dec4-c5ea-11e6-83f1-039b1dd029bd.png)

![mysoc 2016 5](https://cloud.githubusercontent.com/assets/944656/21313593/b67bd726-c5ea-11e6-91a3-c46f58be4d74.png)

![mysoc 2016 4](https://cloud.githubusercontent.com/assets/944656/21313592/b6778ce8-c5ea-11e6-80fc-6e8834b152bf.png)

I was also thinking of doing a few with 'We'll carry on...[helping you write to representatives/making it easy to access politics/supporting people running sites on our software/simplifying the process of writing an FOI request/providing easy-use APIs/contributing to the Open Source community]'.

**Comment by markcridge** [comment]
I'm keen for us to be tweeting cards like these out, but I'd suggest a few design and copy amends;

- There are currently 5 effective lines of copy and too many messages as a result. I'd suggest we simplify these along the lines of;

In 2016 at [mySociety] we

shared free and open data on every politician in the world at EveryPolitician.org

Will you help us with a small donation?
mysociety.org/donate


- Combine the site URL into the middle text rather than splitting
- Always keep 'Will you help us with a small donation?' on one line with the URL underneath
- Can we use the proper mySociety font on everything
- Can we vary the background colours to match the chosen sites? Green for TWFY etc

**Comment by zarino** [comment]
Mysociety font is Source Sans / Source Sans Pro – it looks like you've put these together in Google Slides or Google Drawings. Source Sans should be available in both, via Google Fonts.

**Comment by MyfanwyNixon** [comment]
Thanks @zarino, I've found the font, thanks to the good old Wiki! 
Am putting MarkC's suggestions into practice and they already look better.

**Comment by MyfanwyNixon** [comment]
Thanks for the pointers, @markcridge , these look better:

![mysoc 2016 22](https://cloud.githubusercontent.com/assets/944656/21320676/cb105062-c609-11e6-837c-eba018f3d1ec.png)

![mysoc 2016 21](https://cloud.githubusercontent.com/assets/944656/21320677/cb108a96-c609-11e6-9bdd-cd34ee30e45a.png)

![mysoc 2016 12](https://cloud.githubusercontent.com/assets/944656/21320419/e59fb0a4-c608-11e6-95f3-68a1180450f6.png)

![mysoc 2016 19](https://cloud.githubusercontent.com/assets/944656/21320576/72f48f60-c609-11e6-90ab-599572ceee5d.png)

![mysoc 2016 23](https://cloud.githubusercontent.com/assets/944656/21320428/edbd3702-c608-11e6-954c-c1d773372dde.png)

![mysoc 2016 17](https://cloud.githubusercontent.com/assets/944656/21320575/72f22df6-c609-11e6-8ca6-d04ace1041cb.png)

![mysoc 2016 20](https://cloud.githubusercontent.com/assets/944656/21320431/edc68244-c608-11e6-8d31-34bc9eaa0886.png)

![mysoc 2016 18](https://cloud.githubusercontent.com/assets/944656/21320432/edc8006a-c608-11e6-9350-a9cf8445eebe.png)

![mysoc 2016 13](https://cloud.githubusercontent.com/assets/944656/21320574/72f12e06-c609-11e6-81cf-8728e6deda96.png)

![mysoc 2016 16](https://cloud.githubusercontent.com/assets/944656/21320435/edd599c8-c608-11e6-8d90-c26621088670.png)

![mysoc 2016 15](https://cloud.githubusercontent.com/assets/944656/21320436/eddb674a-c608-11e6-84bd-299c4432f78d.png)

![mysoc 2016 14](https://cloud.githubusercontent.com/assets/944656/21320437/eddd2f1c-c608-11e6-889f-9f4ea26e1397.png)
