### ISSUE TITLE
TICTeC 2017 tote bags

### ISSUE THREAD

**Issue by zarino** [mysociety/internal#16]
https://www.4imprint.co.uk/tag/95/Shopping-and-Tote-Bags/product/400631/Virgo-Shopper-in-Pouch

Dimensions: 395 x 400mm (bag)
Print area: 250 x 250mm (1 side of bag)

![67201](https://cloud.githubusercontent.com/assets/739624/22059629/a277b050-dd65-11e6-9767-055e7936b19e.jpg)

Design to include:
* Logo
* Date
* Location
* #tictec hashtag

Probably on the black / dark grey fabric.

**Comment by zarino** [comment]
The print area is fairly small:

![tote-print-area](https://cloud.githubusercontent.com/assets/739624/22101984/9df34d96-de2d-11e6-8d19-648584b98427.jpg)

So once we’ve put the logo inside it, it'll look something like:

![tote-bag-mockup](https://cloud.githubusercontent.com/assets/739624/22101993/a701b846-de2d-11e6-818e-b41217fa0f16.jpg)

Do you think that’s ok?

**Comment by Gemmamysoc** [comment]
@MyfanwyNixon @Rebeccarumbul What do you guys think of this tote bag design? I personally really like it thanks @zarino My only addition would be the dates (25 & 26 April) if possible, but not essential

**Comment by Gemmamysoc** [comment]
@zarino Just remembered that the printer said they consider this design to be more than one colour (sigh). Is it possible to make the design solid white with no shading? Or does it just look rubbish?

**Comment by Rebeccarumbul** [comment]
love it!

Dr Rebecca Rumbul
Head of Research, mySociety
Email: rebecca@mysociety.org

**Comment by MyfanwyNixon** [comment]
very stylish!

**Comment by zarino** [comment]
@Gemmamysoc Yes, we (or more likely @wrightmartin, as I'll be away next week) will need to redraw the logo, without shading. For the totes and the shirts (#18).

**Comment by wrightmartin** [comment]
All the sighs. but yes, I'll redraw the logo 👍

**Comment by Gemmamysoc** [comment]
New solid colour design:
![screen shot 2017-02-07 at 12 21 58](https://cloud.githubusercontent.com/assets/6806067/22691317/c617636c-ed31-11e6-9e84-6280c3bfbff3.png)

**Comment by wrightmartin** [comment]
Here it is in-situ

![tote-bag-mockup](https://cloud.githubusercontent.com/assets/2292925/22732919/e6867b04-ede7-11e6-985a-be9d6656a12a.jpg)
