### ISSUE TITLE
TICTeC 2017 staff t-shirt

### ISSUE THREAD

**Issue by zarino** [mysociety/internal#18]
Ladies: https://www.banana-moon-clothing.co.uk/womens-tshirts/product/lady-fit-valueweight-t
Men: https://www.banana-moon-clothing.co.uk/t-shirt-printing/product/valueweight-t-shirt

![screen shot 2017-01-18 at 10 10 14](https://cloud.githubusercontent.com/assets/739624/22059818/56cfb110-dd66-11e6-8eec-78265a1ef17e.png)

Design to include:
* “STAFF” in big letters
* Logo, date, location, and #tictec smaller

Probably in purple fabric.

**Comment by zarino** [comment]
Something like this?

![t-shirt-mockup](https://cloud.githubusercontent.com/assets/739624/22063233/a5fac5c2-dd75-11e6-96b9-c075fed87abd.jpg)

**Comment by Gemmamysoc** [comment]
Bec and Myf really like the t-shirt design too! We decided red t-shirts would be the best

**Comment by zarino** [comment]
![t-shirt-mockup](https://cloud.githubusercontent.com/assets/739624/22072234/9245cc42-dd99-11e6-8f59-70e7a2ef5a2e.jpg)
