### ISSUE TITLE
TICTeC 2017 banners and signage

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/internal#24]
Zarino's current versions are here: https://drive.google.com/drive/folders/0B_2LN3vVyLmAaURlQ2FfMXVZakU

**Comment by Gemmamysoc** [comment]
Gemma's feedback: 

General observation: Please could you replace the orange with purple? :) We will have red t-shirts, so I think the orange will clash. I also think purple will go with the surroundings better. 

The logo looks a bit weird on the Illustrator file previews, see:

![logo issue](https://cloud.githubusercontent.com/assets/6806067/23714598/bf993acc-0421-11e7-9531-7d4ab894fa9b.JPG) Not sure if it's just on my computer that it looks weird?

**Courtyard directions:**
Please could you add 'Villa Vittoria' in brackets after 'Palazzo dei Congressi'? The naming conventions they have are really quite confusing, so I'd rather cover both ground just in case :) 

**Villa floors:** 

Please could 'plenary' have a capital 'P'? And could it have a colon afterwards so it makes it more clear that the main plenary is in the Sala Verde? Same with adding a colon after 'Coffee breaks', 'Lunch' and the breakout rooms. Could you name the breakouts 'Breakout A' and 'Breakout B' please? And still include the rooms numbers.

**Comment by zarino** [comment]
- [ ] Use purple not orange
- [ ] "Palazzo dei Congressi" in small, then "Villa Vittoria" in big, below
- [ ] Cap P for Plenary
- [ ] More visual disctinction between the thing that happens in the room ("Main Plenary") and the name of the room itself ("Sala Verde")
- [ ] The two ground floor rooms are going to be called "Room 4 (Sala 4)" and "Room 9 (Sala 9)" everywhere. Drop the "breakouts".

**Comment by zarino** [comment]
Discussion from Slack:

> **zarino** do you think we have the right "attractions" listed under "Villa Vittoria" on this poster? https://drive.google.com/file/d/0B_2LN3vVyLmARlM3OE53RzhvQXM/view  – just thinking, we don't mention "Meeting rooms" anywhere else, and "Catering area" is an odd choice of words too
>
> **gemma** hmm, good point zarino. I guess we mainly need to say that everything TICTeC is happening in the Villa Vittoria with an arrow pointing over the lawn
>
> **gemma** maybe all we need is: 'For TICTeC, please make your way over to the Villa Vittoria in the Palazzo dei Congressi'

**Comment by zarino** [comment]
@Gemmamysoc I’ve updated the files in https://drive.google.com/drive/folders/0B_2LN3vVyLmAaURlQ2FfMXVZakU – can you tell me if there are any more changes you’d like made?

**Comment by Gemmamysoc** [comment]
These look perfect Zarino, thank you!

**Comment by Gemmamysoc** [comment]
Just noticed I need some more changes please. I need the reception banners 1000mm x 500mm to be split up into four separate ones, copy for each is:

FIRST NAMES
A - F

FIRST NAMES
G - L

FIRST NAMES
M - R

FIRST NAMES
S - Z

Similar to the example here:

![registration desks tictec2017](https://cloud.githubusercontent.com/assets/6806067/24143067/61f25b7a-0e20-11e7-9787-e1eac0efafb6.JPG)

**Comment by Gemmamysoc** [comment]
@Rebeccarumbul Do you think we need any other hanging signs at the registration desks apart from the 4 lettering signs I've specified?

**Comment by zarino** [comment]
Ok @Gemmamysoc – `Reception banners 1000x500mm (plus 3mm bleed).pdf` in https://drive.google.com/drive/folders/0B_2LN3vVyLmAaURlQ2FfMXVZakU has been updated with 4 pages, one for each part of the alphabet.

**Comment by Gemmamysoc** [comment]
Thank you again. I have now sent these to the printers, so I consider this ticket now closed.
