### ISSUE TITLE
Segment Mailchimp mailing list

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/internal#25]
This is an action out of this week's Board Meeting. Segmentation will allow us to target our messaging much more efficiently. We can create separate silos, but will still have the ability to message everyone, or combinations of segments.

We've agreed the fundamentals, but the details need more refinement, so please add your thoughts.

- [x] Identify any known **council contacts** (@jukesie to identify), and any email addresses ending in .gov.uk (presumably we can just use Mailchimp's own search function) and create a new segment (NB not a new list).

**Question for discussion**: Do we also add the existing [Services](https://us9.admin.mailchimp.com/lists/members/?id=426793#p:1-s:25-so:null) list to this segment? This contains contacts mainly from our Data Breakfasts events, IIRC. If not, do we just ditch that list or shall we send them all an opt-in email ?

- [x] Pull out any known **funders** (@markcridge, @abimysoc  or @paullenz to identify) and create a new Funders segment (NB not a new list).

- [x] **Journalists**: Match any names from our [Alaveteli Pro contacts](https://docs.google.com/spreadsheets/d/1knJtBSjktVf_IUIOXvSMsJiH4EO4E7Nsm1opr7r0V_E/edit#gid=0) and add them to the existing Alaveteli Pro [mailing list](https://us9.admin.mailchimp.com/lists/members/?id=568309#p:1-s:25-so:null).  (Me)

- [x] (To discuss/consider): Send out a single email to everyone on the main list, asking them to check boxes indicating what they are interested in. How do we want to slice this? We need to bear in mind that if we segment too aggressively, we won't have very frequent stories for some sections.

Some possible approaches include:

- Just segment into the areas we've identified, ie Councils/funders/journalists/everyone else
- Segment as above but also invite people to say they're interested in Campaigners' information too
- Segment much more, eg into FOI/Better Cities/Democracy and/or UK/international work with various subsections of these also available...

- [x] <strike>Alter the sign-up form so that people self-select their segment at point of subscription.</strike> - broken out to #31

- [x] (To discuss/consider): Many people will not respond - they may not even open the survey email. Do we want to keep them on the main list? After all they've never unsubscribed so their email address is presumably still active.

- [x] (To discuss/consider): Do we want to know more about our users, while we're asking? Eg optionally they tell us location/gender/ age?

- [x] Myf to discuss frequency and timelines with stakeholders from each of the teams that are now represented by newsletter segments.

**Comment by MyfanwyNixon** [comment]
By the way - the main newsletter list is here: https://us9.admin.mailchimp.com/lists/members/?id=425649#p:1-s:25-so:null

Log-in details  are on the wiki. 

To create a new segment, go to manage contacts > segments.  I've just done this and identified 680 email addresses ending in gov.uk, which I've put in a segment named 'Better Cities'. 

Rather niftily, there's the option to keep this rule in place as new sign-ups occur.

NB some of these are addresses such as fco.gov.uk and gsi.gov.uk so we (read, @jukesie) may want to comb through these manually.

**Comment by MyfanwyNixon** [comment]
@crowbot How comfortable would you be with having the names on [this sheet](https://docs.google.com/spreadsheets/d/1knJtBSjktVf_IUIOXvSMsJiH4EO4E7Nsm1opr7r0V_E/edit#gid=0) added to our Mailchimp contacts? Not all of them have signed up to hear more about Alaveteli pro but if I understand correctly, all of them have been closely involved with the project and so wouldn't find communications (strictly kept to Alaveteli Pro subject matter) too intrusive?


Having read up a bit, I think we're better importing the Alaveteli Pro list and keeping that as its own segment/group: that way we don't pay Mailchimp twice for anyone who is on the main list *and* the Ala-Pro one (it's possible that there's such a tiny crossover this is negligible, admittedly).

Not sure how feasible this is in terms of the sign-up list though: ideal scenario would be for someone signing up from the Alaveteli Pro page not to have to select from a list of options as to which content they wanted to receive.

**Comment by MyfanwyNixon** [comment]
Additionally: Within the main mailing list, I've added any email address ending in an org.uk or containing one of the major UK charities' names to a segment named 'Campaigners'; I've put any email addresses from major UK media into a segment named 'journalists'.

**Comment by MyfanwyNixon** [comment]
@jacksonj04 Coming out of the above - please could you take the Better Cities segment from Mailchimp (680 contacts which were selected because of their gov.uk email addresses) and remove any which are not council addresses? 

Eg jobcentreplus.gov.uk - not wanted in this segment
lambeth.gov.uk - wanted

Apparently @jukesie has a list of gov domains which could help. I believe that you'll be able to do this more quickly as an automated task than I can manually!

When I say 'remove', I mean please take the non-council addresses out of this segment; they can remain in the main mySociety newsletter list. Thank you!

**Comment by MyfanwyNixon** [comment]
Nudging @jacksonj04 for the above, if you're not too busy - @abimysoc can we consider this an internal priority?

**Comment by jacksonj04** [comment]
I've created a new manual segment for the Better Cities list, which mostly involved stripping non-relevant emails out. However, this will not apply to future emails which sign up.

After looking at the MailChimp API for segmenting, I think we should be able to automate the creation and maintenance of an auto-updating segment(s) if we have a list of domains for councils we're interested in. I'm not sure if there is an upper limit on the number of rules we can have for a segment though, so wouldn't like to suggest this as a silver bullet.

**Comment by MyfanwyNixon** [comment]
@jacksonj04 Thanks Nick. That'd be great if we were able. I guess it should be looked at in concert with https://github.com/mysociety/internal/issues/26.

**Comment by jacksonj04** [comment]
There is also the caveat that we have no guarantee those people are actually in "better cities" areas of work, so this would actually become a "local government" segment.

**Comment by MyfanwyNixon** [comment]
Yeah, I think that's understood - we've hit the same issue with the 'journalist' and 'funder' segments.

**Comment by jukesie** [comment]
Is there somewhere I can have a look at the new local gov list?

**Comment by MyfanwyNixon** [comment]
@jukesie Go to https://us9.admin.mailchimp.com/lists/members/?id=425649#p:1-s:25-so:null (password should be on the wiki) then 'view saved segments'.
