### ISSUE TITLE
Identify all spots for newsletter sign-up

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/internal#26]
Not putting this on #orgsites just because some of the newsletter sign-up opportunities might be in places other than the website.

**Comment by MyfanwyNixon** [comment]
It's worth remembering that we're segmenting the current newsletter list into different areas, but there will still be one big list that consists of everyone. So there's still the chance to send out wide newsletters to all, should we so desire.

- [ ] First: need to rework the ['Subscribe' page](https://www.mysociety.org/subscribe/) so that you can choose the areas you are interested in. 
- [ ] There's already an option to add a newsletter sign-up form to blog posts but it'd be good if this could be stream-specific to reflect the content of the post

### Places for Better Cities sign-up

- [ ] https://www.mysociety.org/better-cities/ (make part of new text as per https://github.com/mysociety/orgsites/issues/924)
- [ ] New FMS for Councils page as per https://github.com/mysociety/FixMyStreet-Commercial/issues/815
- [ ] FMS for Councils case studies, including [Zurich](https://www.mysociety.org/better-cities/fixmystreet/case-study-zuri-wie-neu/), [Barnet](https://www.mysociety.org/better-cities/case-study-fixmystreet-and-barnet-borough-council/), [Oxfordshire](https://www.mysociety.org/better-cities/fixmystreet/case-study-oxfordshire-fixmystreet/) and any new ones we're in the process of creating.
- [ ] At the foot of blog posts on Medium (or wherever we decide to host Jukesie's Better Cities posts)
- [ ] Add simple text link to email footers of Better cities team
- [ ] On the FMS Facebook page (currently links to generic mySociety newsletter)

...Any more?

### Places for Alaveteli Professional sign-up
 - [x] We already have it on the [Ala-Pro page](https://www.mysociety.org/freedom-of-information/alaveteli-professional/)
- [ ] On [the FOI page](https://www.mysociety.org/freedom-of-information/) which is also due to be reworked 
- [ ] Within the Ala-Pro area once people have logged in? Or on the wider WDTK site?
- [ ] On the WDTK Facebook page (currently links to generic mySociety newsletter)

...Any more?

### Places for Campaigners sign-up
- [ ] On each of [the 'how to use WTT for a campaign' pages](https://www.writetothem.com/about-campaigns)
- [ ] On the '[simple campaigning software' blog post](https://www.mysociety.org/2014/03/04/writetothem-simple-campaigning-software/) that I'm always linking to
- [ ] On a reworked [Democracy page](https://www.mysociety.org/democracy/)
- [ ] Somewhere suitable on TWFY?

.. Any more?

**Comment by MyfanwyNixon** [comment]
https://github.com/mysociety/fixmystreetforcouncils/issues/206

**Comment by abimysoc** [comment]
I think the spots have all been identified, so I'm closing this ticket in the optimistic belief that tickets have been created elsewhere for all the changes that need to be made as a result. :)
