### ISSUE TITLE
bot to autopopulate Pipedrive's "Organisations" in the wiki

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/internal#3]
Having a bot that auto-created a page (if necessary) and auto-populated an inbox (if necessary) for the organisations in Pipderive would be excellent. 

The infox box already exists: see https://wiki.mysociety.org/wiki/Sinar_Project

This is also brings the `country` field into a world of (wiki) search (as well as dropping the organisations into the country-based categories automatically) which is superuseful because Pipedrive doesn't currently allow search on country (a bug).

We're already creating and linking to orgs in the wiki, so this is sensible join-the-dotting. 

Incidentally, I don't feel anything like the same need for adding individuals (that is, contacts) in this fashion; my main concern here is that it's supereasy for someone investigating on the wiki to either explicitly or implicitly discover which groups we've been operating with in a country, since that's often the scope of our work. It feels that most contacts we have are (or should) be members of an organisation anyway (with some disclaimers: Pipedrive doesn't happily allow membership of more than one org, but meh).

**Comment by struan** [comment]
If I'm correct these are now in the wiki and all marked as work needed which is making that category a bit unhelpful - 1000+ entries - so it might be better if they didn't end up there.

**Comment by jacksonj04** [comment]
They are all now in the wiki, and *were* marked up with the `{{undocumented}}` template which put them in the "Work Needed" category. The latest version of the bot strips this tag back out, as (like you said) it puts 1000+ pages into the category. MediaWiki will need to catch up on what's actually changed though, so the category page might be out of sync for a short while.

**Comment by struan** [comment]
Ah cool. Thanks!
