### ISSUE TITLE
TICTeC@Taipei postcard

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/internal#30]
Here is the copy for the postcard: https://docs.google.com/document/d/1Z0xCClTihTapm74lFqlLVrmxTQGO2srM-EbX5N2hQ4Y/edit 

Just a standard A6 size please.

**Comment by zarino** [comment]
A6 with 3mm bleed, PDF here: https://drive.google.com/file/d/0B_2LN3vVyLmAVjZCVGRxYllIZDg/view

![flyer](https://cloud.githubusercontent.com/assets/739624/24548583/d2a2c13a-160d-11e7-9af9-e2f4e5526dd0.jpg)

**Comment by abimysoc** [comment]
Buddhist

**Comment by zarino** [comment]
@abimysoc Good catch! :+1:
