### ISSUE TITLE
Linking our Medium estates

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/internal#32]
On Medium, we currently have:
- An [@mySociety account](https://medium.com/@mySociety), which can write posts under the name mySociety
- [a mySociety Publication](https://medium.com/from-mysociety), which can gather together writing from a variety of invited writers and present them in a magazine format. This currently contains pieces from ourselves, from MarkC, Alex, Emily etc.
- [The @EveryPolitician Bot account](https://medium.com/@everypolitician/)

We are about to have:
- A new Better Cities blog which will be piped through to the Better Cities section of FixMyStreet
- (possibly) A WDTK blog which will publish 'this week in FOI' posts.

What I want to do:

- Bring all these blogs together under a single banner, so that when you visit one mySociety publication, you can see that we have a variety of offerings, and choose the one you're most interested in.

So I created two new Publications:
[mySociety Better Cities](https://medium.com/mysociety-better-cities) - for Jukesie to work with
[mySociety for Coders](https://medium.com/mysociety-for-coders) - where I've pulled in all the EveryPolitician Bot posts and we could add anything tecchie there in the future too.

@Jukesie told me how to link to other sites using the 'promo' section but although I've managed this it looks like a steaming pile of doo-doo as you can see [here](https://medium.com/mysociety-for-coders), for example.

I think this is as far as I can go though, so I reckon it's now either a design job or a dev job... or possibly a 'pay for your medium account' job?

Meanwhile I am now going to go and update the wiki with some guidelines about our use of Medium.

**Comment by jukesie** [comment]
I think the easiest way is to consolidate around the mySociety publication - get a header designed and use the Publication navigation options to link to the other Publications (with them set up in a similar format linking back to mySociety pub..)

I can probably take a stab at this at some point if it is helpful..

We can also then do something like point medium.mysociety.org at the Publication as well?

**Comment by wrightmartin** [comment]
I've done a couple of things
- Standardised the promotional boxes across all 3 publications
- Interspersed stories between promotional stuff for other publications

I'm putting together a new photo for the header (and also all of our other social media headers) but that won't be finished until July after the team meeting because we need new photos
