### ISSUE TITLE
Update the photo mosaic background for social media headers

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/internal#33]
- Remove ex-staff :(
- Put in new staff \o/

Will require new photos at the July team meeting

**Comment by MyfanwyNixon** [comment]
Please add https://www.flickr.com/photos/mysociety/ to this as well, thanks!

**Comment by wrightmartin** [comment]
For some reason github isn't letting me upload directly to here, but the new file is https://drive.google.com/drive/folders/1oYzkDp5f6u0NSC8TJYxdHUFIC5ApaD8W

**Comment by abimysoc** [comment]
Done.
