### ISSUE TITLE
Template cards for tweeting

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/internal#35]
@Rebeccarumbul had this idea: a template for 'cards' such as seen here:
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/ParadisePapers?src=hash&amp;ref_src=twsrc%5Etfw">#ParadisePapers</a> show gaping loopholes in global financial system - UK services, territories &amp; systems complicit! <a href="https://t.co/6dKAuBn9ub">https://t.co/6dKAuBn9ub</a> <a href="https://t.co/oFSfm4AdYM">pic.twitter.com/oFSfm4AdYM</a></p>&mdash; Transparency Int&#39;lUK (@TransparencyUK) <a href="https://twitter.com/TransparencyUK/status/927259873057869825?ref_src=twsrc%5Etfw">November 5, 2017</a></blockquote>

They'd be ready and waiting so that when there was something in the news we wanted to comment on, we could just drop the text in (and maybe an image?). Bec mentions America getting rid of EITI as a topic we would have an opinion on and where it's good to put out a quick response. But equally 'newsy bits and quotes from MarkC' :)

Last year we did these for TICTeC: https://drive.google.com/a/mysociety.org/file/d/0B_2LN3vVyLmAX3g3U3NFNXd6OG8/view?usp=sharing Same general idea; I guess the difference here is that they'd be easily editable by anyone for quick response.

**Comment by abimysoc** [comment]
https://docs.google.com/presentation/d/1IlEDRk2Pbt3EAiRCf9Fr19Z9cv3yaIwSYg7yJyNAwvQ/edit now exists.
