### ISSUE TITLE
Privacy policy for Pledgebank - check and deploy

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/internal#36]
I'm putting this in Internal because I have a feeling the Pledgebank repo might not be monitored by many people.

Here's a new GDPR-compliant privacy policy which also reflects the fact that the site is archived: https://docs.google.com/document/d/1T0Pz0hqdbWYinISB_FHp_Bv9gGqOTgY4Mkkji1Q35bU/edit#

**Comment by dracos** [comment]
It is suggested we simplify this by scrubbing the database of all non-visible personal data (e.g. email addresses, phone, facebook ID).

**Comment by dracos** [comment]
```
pb=# update person set mobile=null;
pb=# delete from facebook ;
pb=# update person set facebook_id=null where facebook_id is not null;
pb=# update person set email=null where email is not null;
pb=# update person set password=null where password is not null;
pb=# update comment set email=null where email is not null;
pb=# delete from smssubscription  where outgoingsms_id is not null;
pb=# delete from outgoingsms ;
pb=# update signers set ipaddr =null where ipaddr is not null;
pb=# delete from requeststash ;
pb=# delete from token;
pb=# delete from translator ;
```
