### ISSUE TITLE
mySociety.org home page text amend

### ISSUE THREAD

**Issue by markcridge** [mysociety/internal#41]
Under Better Cities link please change the copy 'Complete reporting tools that cut costs for councils and citizens' to 'Tools for improving your community for citizens and public servants'.

(This will fix the annoying misalignment of text if it pushes it on to three lines)

**Comment by abimysoc** [comment]
I don't like the repeated 'for' in the suggested wording. @MyfanwyNixon make it better?

**Comment by MyfanwyNixon** [comment]
>Tools to help citizens and public servants improve their local communities.
