### ISSUE TITLE
TICTeC 2018 'share graphic' 

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/internal#44]
I want an eye-catching image I can use when advertising TICTeC on Facebook Groups. I'd also like to use the image on my Twitter cover photo. 

I'd like the image to include:

TICTeC 2018
The Impacts of Civic Technology Conference
Lisbon, 18 & 19 April 2018

Call for session proposals now open!
Apply and register here: tictec.mysociety.org

**Comment by zarino** [comment]
Something like these?

![facebook-image-orange](https://user-images.githubusercontent.com/739624/33942601-5a8326b0-e00e-11e7-9c6c-c25a33729d51.png)

![facebook-image-purple](https://user-images.githubusercontent.com/739624/33942611-5dac3f34-e00e-11e7-91e2-d616a414c3dc.png)

![twitter-header](https://user-images.githubusercontent.com/739624/33942618-6046586a-e00e-11e7-91c5-f1817a25eb13.png)

**Comment by Gemmamysoc** [comment]
Thanks Zarino, these look great! :)
