### ISSUE TITLE
External facing slack channels

### ISSUE THREAD

**Issue by GeorgieBurr** [mysociety/internal#49]
**Issue:** 
Within the Democracy Team, we currently have 3 external channels with international partners.  These work well for having 1:1 conversations with partners, but they do not facilitate volunteers to talk to / learn from each other and build a community feeling. 

**Proposed solution:**
My initial thinking was to create an external mySociety slack, which people could join through the website and they could choose to join relevant channels for the products/ projects they are interested in, e.g EveryPolitician, Democratic Commons, Write in Public, Alaveteli, Volunteering etc etc (to be defined)

However, I now realise we have had multiple attempts of this approach (Gareth pointed me to the slack Wiki).

Instead, I would be grateful if people to let me know anything they learned through their external facing slack: what worked, what didn't, is it still being used? If not, why not etc tec.  I would be interested in any solutions proposed for the above issue.

**Comment by abimysoc** [comment]
I think a Democratic Commons Slack would help reinforce the "this is a community of which mySociety is a part" message, rather than "everything happens in mySociety's Slack and you can't come in unless we invite you".

**Comment by struan** [comment]
IME the Democracy Club slack works pretty well and while it's largely centred around their work it also seems to be a general hub for elections related civic tech in the UK. However, I think it that's partly as it's a small community and largely made up of people who know each other.

Given the breadth of the Democratic Commons work it seems to me that multiple channels would be required in order to make it manageable because not everyone is interested in boundary data and the structure of the Peruvian legislature, and that points towards an external slack.

Side thought, I also wonder if there would be a value in a TICTeC external slack/channel?

**Comment by GeorgieBurr** [comment]
An updated current proposal, from Nick in Dem team, in relation to how we communicate with a new partner, who wants a slack channel:
1 - if they have a Slack already, we can create a shared channel. This is what we’ve done with eg g0v
2 - if we just want a few people, we can invite them to our Slack as single channel guests
3 - We create a whole new free Slack, using something like Slackin to let people join, and we can set up extra private channels on that if we want

Nick suggests for community space, option 3 and I concur...

**Comment by GeorgieBurr** [comment]
And, another thing to be aware of, for option 3 (thank Nick)
Is that it would have to be a free slack (otherwise someone would have to pay a _lot_ for all the users), which means restrictions on how far back history goes

**Comment by abimysoc** [comment]
The mySociety Slack workspace is on a paid plan for free via https://get.slack.help/hc/en-us/articles/204368833-Slack-for-Nonprofits

They have a "one workspace per organisation" rule so we couldn't get another one, but potentially some partner organisation who don't already have a Slack of their own might be eligible.

**Comment by GeorgieBurr** [comment]
Thanks for all your input to date team mates. An update is that the Democracy team have come up with a sloution, so from my point of view I am ready to close the issue. 

We will use the single channel function for all Democratic Commons related work, with partners and staff working together to support the concept  (and seperate concorde into a different channel). 
https://get.slack.help/hc/en-us/articles/202518103-Multi-Channel-and-Single-Channel-Guests

If you are interested in how I think will support a DC community you can read about it here:
https://docs.google.com/document/d/14y64SLLOgT2ATdy4lk28PYY2ztqKA2gz3LykMaA_SPI/edit

**Comment by Gemmamysoc** [comment]
I was just commenting on this but I see you've resolved it :) From my point of view, I find the [TICTeC](https://groups.google.com/forum/#!forum/tictecbymysociety), [Alaveteli Users](https://groups.google.com/forum/#!forum/alaveteli-users) and [Alaveteli Dev](https://groups.google.com/forum/#!forum/alaveteli-dev) Google Groups work well for the requirements we have (so I wouldn't be interested in public Slack channels for those). One of the Australian Alaveteli re-users set up an Alaveteli Slack workspace after our AlaveteliCon gathering in 2015 and to be honest noone uses it, but people still use the Google Groups.

**Comment by garethrees** [comment]
I think Gemma's covered the gist of what I was going to say.

The main _reason_ for it not working well for us was that its too easy to miss stuff in real-time chat when _we're_ the ones someone is expecting a response from. Yeah there are `@`-mentions, but that's really distracting from scheduled work. Mailing list topics are far easier to triage and schedule during sprint planning. There's generally never a need for an _instant_ response, either.

RTC is great if people want to generally chat or collaborate if they're both working on the same thing together, but for interaction that's more like "user support", real time chat isn't as good as the mailing lists – for us – given our current capacity and priorities.
