### ISSUE TITLE
Newsletter names /descriptors

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/internal#52]
Currently on https://www.mysociety.org/subscribe/:

![screenshot_2018-09-24 newsletters mailing lists](https://user-images.githubusercontent.com/944656/45946920-4a069d00-bfea-11e8-9607-bff21c05783a.png)

I think this is hard-coded.
Can we change
>News about better cities and councils 

to 

>News about community and councils 

and 
>News about Freedom of Information and journalism 

to

> News about FOI, transparency and journalism 

(I'm feeling like we should keep FOI in there as it is a definite pull for those who want it)

Then we'll need to also reflect this on any of the single-stream sign up forms we have around.

**Comment by garethrees** [comment]
> (I'm feeling like we should keep FOI in there as it is a definite pull for those who want it)

+1
