### ISSUE TITLE
Make volunteers@whatdotheyknow.com a Google Group rather than mailing list

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/internal#66]
Reasons:

Transparency@
* Enables WhatDoTheyKnow volunteers and others to see what the wider transparency team are doing. 

Volunteers@ 
* Enables WhatDoTheyKnow volunteers to volunteer without having to have personal data held by mySociety shared with them on their personal email addresses. 
* Enables WhatDoTheyKnow volunteers to volunteer without having to deal personally with deleting email prior to the expiry of the retention period. 

I'd suggest a 2 year retention period on volunteers@whatdotheyknow.com 

Vaguely related:

* https://github.com/mysociety/internal/issues/65 
* https://github.com/mysociety/whatdotheyknow-theme/issues/1213

**Comment by garethrees** [comment]
`transparency@` is just an alias of https://groups.google.com/a/mysociety.org/g/alaveteli

**Comment by garethrees** [comment]
This is done https://groups.google.com/a/mysociety.org/g/wdtk-volunteers (via https://github.com/mysociety/sysadmin/issues/1672)
